### ISSUE TITLE
Running npm install does not install all dependencies

### ISSUE THREAD

**Issue by bsilverm** [SalesforceCommerceCloud/create-commerce-app#39]
The readme currently states to run npx create-commerce-app, then to run npm install, however doing so does not install all the dependencies and running the app fails as a result.  Can we please update the readme to reflect the instructions found in [CCDC](https://developer.commercecloud.com/s/build-apps-with-apis-getting-started) (running yarn/yarn build/yarn start)?

**Comment by bredmond-sf** [comment]
Hi Ben, the README does link to the sample apps README and instructs the user to run yarn:

> In order to run your new application, please follow the instructions for the sample Salesforce Commerce Storefront app. You don't need to clone the sample apps repo, but you do need to run the yarn commands shown in the root directory of your new commerce app.

The instruction to run npm install is in the Setup section which says that it's for building create-commerce-app locally, not for the sample app that it installs.

**Comment by bsilverm** [comment]
Ah, makes sense.. This came from a customer request and I thought we could clear it up as they got stuck here.  Perhaps we can just state the purpose of why one might want to build the create-commerce-app locally vs using the Quick Start instructions?  I've notice some of our repos have customer facing tasks in the README, and then some tasks meant more for an internal developer.

**Comment by bredmond-sf** [comment]
@bsilverm I've moved the info for building and testing to CONTRIBUTING.md so the README is now focused on usage.
