### ISSUE TITLE
Sample app doesn't work

### ISSUE THREAD

**Issue by danechitoaie** [SalesforceCommerceCloud/create-commerce-app#72]
I just followed the following steps to get this sample app working:
1. `npx create-commerce-app your-app-name`
2. `cd your-app-name`
3. `yarn install`
4. `yarn run start:dev`

And it fails with following error:
```
storefront-lwc: Error: Cannot find module '@sfcc-core/core'. Please verify that the package.json has a valid "main" entry] {
storefront-lwc:   code: 'MODULE_NOT_FOUND',
storefront-lwc:   path: '/Users/daniels/Desktop/your-app-name/node_modules/@sfcc-core/core/package.json',
storefront-lwc:   requestPath: '@sfcc-core/core'
storefront-lwc: }
storefront-lwc: [nodemon] app crashed - waiting for file changes before starting...
```

I'm running this on `NodeJS v12.20.1`

**Comment by bredmond-sf** [comment]
Hi @danechitoaie It looks like you've left out the `yarn build` step (step 6 https://github.com/SalesforceCommerceCloud/sfcc-sample-apps ) which creates the `@sfcc-core/core` module. Please run that and try `yarn start:dev` again.

**Comment by danechitoaie** [comment]
Yes, I was missing that step. Was following some guide which might be outdated that did not had the yarn build step. Thank you.
